# Nodes with values to reuse in the pipeline.
common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.1.0

steps:

  - label: "Unit tests"
    command: |
      yum install shasum
      echo "--- 🧪 Testing"
      cp gradle.properties-example gradle.properties
      ./gradlew testJalapenoDebug
      ./gradlew lib:cardreader:testDebug
      echo "--- ⚒️ Generating and uploading code coverage"
      ./gradlew jacocoTestReport
      curl -Os https://uploader.codecov.io/latest/linux/codecov
      chmod +x codecov
      ./codecov -t $CODECOV_TOKEN
    plugins: *common_plugins
